import About from '@/comps/About';
import Footer from '@/comps/Footer';
import Hero from '@/comps/Hero';
import Portfolio from '@/comps/Portfolio';
import Skills from '@/comps/Skills';
import Testimonials from '@/comps/Testimonials';
import Title from '@/comps/Title';
import Head from 'next/head'
import { useEffect, useState,useCallback } from "react"

export default function Home() {
  const [count, setCount] = useState(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="./fontawesome/css/fontawesome.css" rel="stylesheet"/>
        <link href="./fontawesome/css/brands.css" rel="stylesheet"/>
        <link href="./fontawesome/css/solid.css" rel="stylesheet"/>
      </Head>
      <div className='fixed w-100 h-100 bg-green-500 z-10'>
        {count} 
      </div>
      
      <div onWheel={ event => {
              if (event.nativeEvent.deltaY > 0 && count < 100) {
                    setCount(count + 1)
              } else if(event.nativeEvent.deltaY < 0 && count > 0){
                setCount(count - 1)
              }
            }}  
            id='container' className="overflow-x-hidden grid h-screen w-screen bg-slate-300">
          
          <div className="fixed z-50 self-center right-5 w-1 bg-gray-200 rounded-full h-4/5 dark:bg-gray-700">
            <div className="bg-blue-600 h-2.5 rounded-full" style={{["height" as any]: count+"%"}}></div>
          </div>
          {count >= 0 && count <= 10 ? <Hero></Hero>: null }
          {count > 10 && count <= 20 ? <About></About>: null }
          {count > 20 && count <= 30 ? <Skills></Skills>: null }
          {count > 30 && count <= 40 ? <Title></Title>: null }
          {count > 40 && count <= 50 ? <Portfolio></Portfolio>: null }
          {count > 50 && count <= 60 ? <Testimonials></Testimonials>: null }
          {count > 60 && count <= 70 ? <Footer></Footer>: null }
      </div>
    </>
  )
}
